#pragma once
#ifndef CONFIG_H
#define CONFIG_H

#define CHIP8_WINDOW_TITLE "dirty8 emulator"
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_WINDOW_MULTIPLIER 10
#define CHIP8_DEFAULT_SPRITE_HEIGHT 5

#define CHIP8_STACK_DEPTH_SIZE 16
#define CHIP8_MEMORY_SIZE 4096

#define CHIP8_PROGRAM_LOAD_ADDRESS 0x200

#define CHIP8_TOTAL_KEYS 16

#endif
